/*
 *  VIDAGE DE LA BASE ET SUPPRESSION
 */

/*
TRUNCATE TABLE PARCOURS;
TRUNCATE TABLE UTILISATEURS;
TRUNCATE TABLE PREINSCRIPTIONS */

DROP TABLE PARCOURS;
DROP TABLE UTILISATEURS;
DROP TABLE PREINSCRIPTIONS;
