/*
 *  VIDAGE DE LA BASE ET SUPPRESSION
 */

/* TRUNCATE TABLE INSCRIPTIONS;
TRUNCATE TABLE PARCOURS;
TRUNCATE TABLE UTILISATEURS;
TRUNCATE TABLE PREINSCRIPTIONS */

DROP TABLE INSCRIPTIONS;
DROP TABLE PARCOURS;
DROP TABLE UTILISATEURS;
DROP TABLE PREINSCRIPTIONS;