/* Vidage de la base et suppression */

/* TRUNCATE TABLE INSCRIPTIONS;
TRUNCATE TABLE PARCOURS;
TRUNCATE TABLE UTILISATEURS; */

DROP TABLE INSCRIPTIONS;
DROP TABLE PARCOURS;
DROP TABLE UTILISATEURS;
